tasks:
  - name: Open dash app in a new browser window
    command: |
      port=8501
      gp await-port "$port" && gp preview "$(gp url "$port")" --external

  - name: Run streamlit app
    init: |
      pip install -r requirements.txt
    command: |
      PORT=8501
      url=$(gp url "$PORT")
      HOST=${url#"https://"}
      DASH_DEBUG=0
      python app.py
